execute if score @s actual_health matches 1 run scoreboard players set @s health 1
execute if score @s actual_health matches 2 run scoreboard players set @s health 2
execute if score @s actual_health matches 3 run scoreboard players set @s health 3
execute if score @s actual_health matches 4 run scoreboard players set @s health 4
execute if score @s actual_health matches 5 run scoreboard players set @s health 5
execute if score @s actual_health matches 6 run scoreboard players set @s health 6
execute if score @s actual_health matches 7 run scoreboard players set @s health 7
execute if score @s actual_health matches 8 run scoreboard players set @s health 8
execute if score @s actual_health matches 9 run scoreboard players set @s health 9
execute if score @s actual_health matches 10 run scoreboard players set @s health 10
execute if score @s actual_health matches 11 run scoreboard players set @s health 11
execute if score @s actual_health matches 12 run scoreboard players set @s health 12
execute if score @s actual_health matches 13 run scoreboard players set @s health 13
execute if score @s actual_health matches 14 run scoreboard players set @s health 14
execute if score @s actual_health matches 15 run scoreboard players set @s health 15
execute if score @s actual_health matches 16 run scoreboard players set @s health 16
execute if score @s actual_health matches 17 run scoreboard players set @s health 17
execute if score @s actual_health matches 18 run scoreboard players set @s health 18
execute if score @s actual_health matches 19 run scoreboard players set @s health 19
execute if score @s actual_health matches 20 run scoreboard players set @s health 20
execute if score @s actual_health matches 21 run scoreboard players set @s health 21
execute if score @s actual_health matches 22 run scoreboard players set @s health 22
execute if score @s actual_health matches 23 run scoreboard players set @s health 23
execute if score @s actual_health matches 24 run scoreboard players set @s health 24
execute if score @s actual_health matches 25 run scoreboard players set @s health 25
execute if score @s actual_health matches 26 run scoreboard players set @s health 26
execute if score @s actual_health matches 27 run scoreboard players set @s health 27
execute if score @s actual_health matches 28 run scoreboard players set @s health 28
execute if score @s actual_health matches 29 run scoreboard players set @s health 29
execute if score @s actual_health matches 30 run scoreboard players set @s health 30
execute if score @s actual_health matches 31 run scoreboard players set @s health 31
execute if score @s actual_health matches 32 run scoreboard players set @s health 32
execute if score @s actual_health matches 33 run scoreboard players set @s health 33
execute if score @s actual_health matches 34 run scoreboard players set @s health 34
execute if score @s actual_health matches 35 run scoreboard players set @s health 35
execute if score @s actual_health matches 36 run scoreboard players set @s health 36
execute if score @s actual_health matches 37 run scoreboard players set @s health 37
execute if score @s actual_health matches 38 run scoreboard players set @s health 38
execute if score @s actual_health matches 39 run scoreboard players set @s health 39
execute if score @s actual_health matches 40 run scoreboard players set @s health 40